= VideoTimeMeasure

This application measures time in video clip. Wide range of formats are supported to measure time directly in camcorder's native video format.

Use video from camcorders or hardware encoders. Software encoders can damage time information in video even running on powerful hardware.

== Basic usage
 . Open video file by selecting 'Open' item in 'File' menu.
 . Select desired timestamp cell in table right to the video image.
 . Navigate to time using arrow buttons below video.
 . Continue to next timestamp. (Press enter on insert row and use mouse.)

== Scripting
Scripts allow to further process measured intervals for example to points or process data according to sport specific requirements.

Each cell excluding cells used for intervals measurement and summary can contain script. There are also whole column and row scripts.
Cells in rows of measured intervals can contain whole column scripts only.

Scripting language is JavaScript, so basic programming skill is necessary to create script.

=== Profiles
Scripts in table are called profile. User can switch between profiles to easily manage different match types.
Choose desired profile in 'Script profiles' menu.

Profiles are stored in user's application data directory.

=== Environment variables
Environment variable provide information about cell position in table and measured intervals.

row::
    Current row starting from 0.
column::
    Current column starting from 0.
intervals::
    Number of measured intervals.
table.getValue(row, column)::
    Function returns value of cell specified by row and column.
table.printf(format, number)::
    Function returns formatted number. 'Format' argument is the same as for standard C printf function.

Rows with measured intervals contain additional variables:

start::
    Interval start in seconds.
stop::
    Interval stop in seconds.
duration::
    Interval duration in seconds.

=== Editing scripts
 . Check 'Edit' item in 'Script profiles' menu.
 . Right click on table to add column or row.
 . Right click on desired cell, row or column header to edit cell, whole row or column script.

In 'Script profiles' menu:

Clear::
    Removes script from table and deactivates current profile.
Import::
    Imports profile from archive file.
Export::
    Exports profile to archive file.
New::
    Creates new script profile. If there are scripts in table, the scripts are copies to newly created profile.
Delete::
    Deletes selected script profile. Profile scripts are not removed immediately from table to allow undo by creating new profile.
Get examples::
    Creates script profile examples. There are 2 examples:
    . 'Trampoline individual example' demonstrates formatting interval duration according to specific requirements.
    . 'Trampoline synchronous example' demonstrates  converting intervals to points.

== Running and compilation

Dependencies for compilation or dynamically linked binary::
 - Qt 4.8
 - FFmpeg
 - Boost library
Compilation::
 - Linux: qmake or qt creator
 - Windows: I use MXE cross compilation environment on Linux
Sources::
https://github.com/jankolorenc/VideoTimeMeasure
Problem description::
https://jankolorenc.github.io/2015/05/20/Measuring-time-in-video.html

Thanks to all people who created libraries, tutorials and tools used to create this application.
